"""
Simple Calculator GUI Application

This script implements a basic calculator GUI using the tkinter library. Users can perform simple arithmetic operations
(addition, subtraction, multiplication, division) and clear the input using the "C" button.

Usage:
    1. Run the script.
    2. The GUI window will appear with a display label and buttons for digits, operators, ".", "=", and "C".
    3. Click the buttons to input digits and operators and see the calculated result on the display.
    4. Press "C" to clear the input.

Author: Hamza El Sousi
GitHub: https://github.com/HamzaElSousi

"""


import tkinter as tk

def button_click(event):
    """
    Event handler for button clicks.

    Args:
        event (tkinter.Event): The event generated by button click.

    """
    current_text = result_label['text']
    button_text = event.widget['text']
    if button_text == "=":
        try:
            result = eval(current_text)
            result_label['text'] = str(result)
        except:
            result_label['text'] = "Error"
    elif button_text == "C":  # Reset button
        result_label['text'] = ""
    else:
        result_label['text'] = current_text + button_text

# Create the main window
root = tk.Tk()
root.title("Simple Calculator")

# Create widgets
result_label = tk.Label(root, text="", font=("Helvetica", 18))
button_texts = ["7", "8", "9", "/", "4", "5", "6", "*", "1", "2", "3", "-", "0", ".", "=", "+"]
buttons = [tk.Button(root, text=text, padx=20, pady=20) for text in button_texts]

# Add the reset button
reset_button = tk.Button(root, text="C", padx=20, pady=20)
buttons.append(reset_button)

# Layout widgets
result_label.grid(row=0, column=0, columnspan=4)
row_num, col_num = 1, 0
for button in buttons:
    button.grid(row=row_num, column=col_num)
    col_num += 1
    if col_num == 4:
        col_num = 0
        row_num += 1

# Attach event handlers
for button in buttons:
    button.bind("<Button-1>", button_click)

# Start the GUI event loop
root.mainloop()
